version: '3'

dotenv: ['.env']

vars:
  PORT: '{{.PORT}}'

tasks:
  default:
    desc: Run the development server with live reload
    cmds:
      - task: dev

  build:
    desc: Build all assets and the binary sequentially
    cmds:
      - templ generate
      - bunx @tailwindcss/cli -i static/css/input.css -o static/css/app.css --minify

  dev:
    desc: Run all watch tasks concurrently (recomended for development)
    cmds:
      - |
        bunx concurrently --kill-others \
          --prefix "[{name}]" \
          --names "TEMPL,CSS,TUNNEL" \
          --prefix-colors "blue,magenta,cyan" \
          "task templ" \
          "task css" \
          "task cloudflared"

  templ:
    desc: Watch templates and run the server with live reload
    cmds:
      - templ generate --watch --proxy="http://localhost:{{.PORT}}" --cmd="go run main.go"

  cloudflared:
    desc: Run cloudflared tunnel
    cmds:
      - cloudflared tunnel run dev

  css:
    desc: Watch and build Tailwind CSS
    cmds:
      - bunx @tailwindcss/cli -i static/css/input.css -o static/css/app.css --watch --minify

  test:
    desc: Run all tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- ./...

  test:watch:
    desc: Run tests and watch for changes
    cmds:
      - gotestsum --watch --format pkgname-and-test-fails -- ./...
