version: '3'

dotenv: ['.env']

vars:
  PORT: '{{.PORT}}'

tasks:
  default:
    desc: Run the development server with live reload
    cmds:
      - task: dev

  dev:
    desc: Watch templates and run the server with live reload
    deps: [cloudflared, templ, css]

  templ:
    desc: Watch templates and run the server with live reload
    cmds:
      - templ generate --watch --proxy="http://localhost:{{.PORT}}" --cmd="go run main.go"

  cloudflared:
    desc: Run cloudflared tunnel
    cmds:
      - cloudflared tunnel run dev

  css:
    desc: Watch and build Tailwind CSS
    cmds:
      - bunx @tailwindcss/cli -i static/css/input.css -o static/css/app.css --watch --minify

  test:
    desc: Run all tests
    cmds:
    - gotestsum --format pkgname-and-test-fails -- $(go list ./... | grep -v "^github.com/torresposso/gosmic-code$")

  test:watch:
    desc: Run tests on file changes
    cmds:
    - gotestsum --watch --format pkgname-and-test-fails -- $(go list ./... | grep -v "^github.com/torresposso/gosmic-code$")
